### ISSUE TITLE
Add a bell sound option at the end of a sutta

### ISSUE THREAD

**Issue by Aminah-SC** [sc-voice/sc-voice#37] opened 2019-03-27 06:57 UTC
#### User story

When I use Voice I don't always know when a sutta has ended, a bell at the end would help know. 

#### Feature description (the list of things that need to be done for the ticket to be considered finished):

- [ ] option in settings for end bell 

#### Pre release planning check:
- [ ] Small enough to completed in a milestone.
- [ ] Dependencies marked
- [ ] No external dependencies block this from being completed.
- [ ] Details are understood by dev team so they know what needs to be done and can determine if it can be completed.

**Comment by firepick1** [comment] 2019-04-11 17:13
This was so generally useful that I just made the code use the same sound at the end as at the beginning. So essentially the bell setting is for both.

v1.4.6

**Comment by firepick1** [comment] 2019-04-24 13:19
Fixed in v1.4.12. Issue was staging server not updating to latest release

**Comment by Aminah-SC** [comment] 2019-04-27 07:55
@firepick1 This is brilliant thanks so much. Most definitely :+1: from me for v1.4. 

@sabbamitta Ordinarily, I'd close this issue, but feel that a further development issue arises from it so I've assigned to you to determine and act on as you see fit:

While for me this is a valuable addition, it is important that it is an option not an imposition. In turn, it would probably be good if a separate setting option was included. The simplest might be to just add one more option, something like "Play end bell". As part of the potential spec, to keep things trim and not overload users with options, I would suggest removing the rainforest option and either the bell by Coemgenu or by JetRye (they are fairly similar).

**Comment by sabbamitta** [comment] 2019-04-29 11:58
Agreeing that there is already the option turning off all sounds, the issue is now closed.

**Closed by sabbamitta** 2019-04-29 11:58 UTC
Labels: P3, Type: new feature
