### ISSUE TITLE
Research ways to lessen pause between each segment

### ISSUE THREAD

**Issue by michaelh-sc** [sc-voice/sc-voice#156] opened 2019-08-05 10:38 UTC
#### Description

There is often a pause between two segments, where the hour glass appears while it is loading the next segment. If there was no pause, and each of the next segments is pulled down ready to play I'd suggest this would be a general usability improvement.

I'd like to suggest researching a node library that is able to pre-load a bunch of different audio files and play them as a playlist after pre-loading:
This comment shows how a playlist can be pre-loaded in howler js: https://github.com/goldfire/howler.js/issues/191#issuecomment-490769770
Howler JS looks to be very popular (used by Disney and lots of media industry), purely Web API with fallback to HTML5.: https://www.npmjs.com/package/howler 

#### Acceptance criteria

- [ ] a plan agreed on by team members
- [ ] if applicable, the creation of a ticket with a spec understood & agreed by team members

**Comment by sabbamitta** [comment] 2019-08-05 11:01
Michael, did this happen on the staging server or on production? If on production, did it also happen for suttas from the KN or DN (Pali Aditi)? If on staging, did it also happen for suttas of the KN, DN or MN (Pali Aditi)? These are sections we have already installed VSMs, and one of the purposes of doing this is to remove latency.

Maybe try Pali with Aditi in DN 33? It should be better.

If not, we may consider looking into howler js (but anyway, this is rather a question to Karl, not to me).

**Comment by firepick1** [comment] 2019-08-05 21:52
The primary reason for a long pause between segments is that the audio is being generated. With VSM technology, that should never happen once we install VSM's for all nikayas and voices.

The other reason for a pause between segments is for emphasis. Segments are semantic units usually on paragraph boundaries that require a slight pause. Those slight pauses are intentional.

**Comment by michaelh-sc** [comment] 2019-08-06 11:04
Staging server for SN so I guess no VSM.
So the audio is being generated in that time - maybe generate the next two before starting the first segment, and then generate/download the one in two segments' time while the others are playing?
Sometimes, the segments are only 4 or so words long, I guess I only notice it because in some recordings the boundaries are in the middle of an utterance but if TTSed then they have a nice pause for emphasis.

**Comment by sabbamitta** [comment] 2019-08-06 11:09
So far we have VSMs for Pali Aditi, no other voice. On staging there are more VSMs installed than on production because currently there is more disk space on staging (will be adapted on production with the next release). On staging we have VSMs. for KN, DN, and MN, all Pali Aditi. So if you are testing something else you will still encounter latencies, but listening to the same sutta a couple of times should fix it. More VSMs will be built over time in a slow pace for billing reasons. Eventually we are aiming at having all Nikayas in all languages for all voices, but this will still be a while.

**Comment by sabbamitta** [comment] 2019-08-07 15:31
The issue is addressed with the building of VSMs. Closing.

**Closed by sabbamitta** 2019-08-07 15:31 UTC
Labels: Type: research
